import type {PracticeDefinition,SkillId} from './developmentTypes'

export const PRACTICES:PracticeDefinition[]=[
  {id:'start-two-minutes',title:'Começar por dois minutos',skill:'self.start_action',description:'Escolha uma ação relevante e faça apenas o primeiro passo durante dois minutos. Ao terminar, decida conscientemente se continua ou encerra.',weeklyDescription:'Em três oportunidades adequadas nesta semana, transforme uma intenção em um primeiro passo de até dois minutos.',estimatedMinutes:2,difficulty:'low',contexts:['geral','energia baixa'],contraindications:[],requiresOpportunity:false,sourceType:'deterministic-template'},
  {id:'new-information-stop-rule',title:'Regra da informação nova',skill:'self.stop_recursive_analysis',description:'Pergunte: surgiu informação nova desde a última vez que pensei nisso? Se não, escreva uma ação capaz de produzir informação nova ou encerre a análise por agora.',weeklyDescription:'Em duas situações de análise repetitiva, use a pergunta “há informação nova?” antes de continuar pensando.',estimatedMinutes:3,difficulty:'low',contexts:['preocupação','decisão'],contraindications:[],requiresOpportunity:false,sourceType:'deterministic-template'},
  {id:'emotion-impulse-action',title:'Emoção, impulso e ação',skill:'emotion.deliberate_response',description:'Quando notar ativação emocional, registre em três linhas: emoção, impulso imediato e ação que você escolhe deliberadamente.',weeklyDescription:'Em até três situações emocionalmente relevantes, separe emoção, impulso e ação escolhida antes de responder.',estimatedMinutes:3,difficulty:'low',contexts:['estresse alto','conflito'],contraindications:[],requiresOpportunity:true,sourceType:'deterministic-template'},
  {id:'uncertainty-open-hypothesis',title:'Manter a hipótese aberta',skill:'flexibility.uncertainty',description:'Escolha uma conclusão ainda incerta e escreva: “o que sei”, “o que não sei” e “o que faria eu atualizar esta conclusão”.',weeklyDescription:'Em duas situações de incerteza, registre o que sabe, o que não sabe e qual informação permitiria atualizar a conclusão.',estimatedMinutes:5,difficulty:'medium',contexts:['incerteza','antecipação'],contraindications:[],requiresOpportunity:false,sourceType:'deterministic-template'},
  {id:'communication-one-sentence-purpose',title:'Uma frase de propósito',skill:'communication.clarity',description:'Antes de uma conversa ou mensagem importante, escreva em uma frase o que você quer que a outra pessoa compreenda.',weeklyDescription:'Antes de três comunicações relevantes, formule em uma frase o objetivo principal antes de acrescentar detalhes.',estimatedMinutes:2,difficulty:'low',contexts:['mensagem','conversa'],contraindications:[],requiresOpportunity:true,sourceType:'deterministic-template'},
  {id:'communication-three-points',title:'Três pontos essenciais',skill:'communication.clarity',description:'Antes de uma comunicação relevante, reduza seu raciocínio a no máximo três pontos que precisam ser compreendidos.',weeklyDescription:'Em duas comunicações relevantes, organize a mensagem em até três pontos antes de explicar os detalhes.',estimatedMinutes:4,difficulty:'medium',contexts:['mensagem','conversa'],contraindications:[],requiresOpportunity:true,sourceType:'deterministic-template'},
  {id:'communication-specific-request',title:'Pedido específico',skill:'communication.assertiveness',description:'Em uma interação adequada, transforme uma expectativa implícita em um pedido específico, observável e respeitoso.',weeklyDescription:'Em uma conversa relevante, formule um pedido específico em vez de depender de que a outra pessoa deduza sua necessidade.',estimatedMinutes:4,difficulty:'medium',contexts:['relações','conversa'],contraindications:[],requiresOpportunity:true,sourceType:'deterministic-template'},
  {id:'communication-question-first',title:'Perguntar antes de responder',skill:'communication.listening',description:'Em uma conversa, faça uma pergunta de compreensão antes de apresentar sua interpretação ou solução.',weeklyDescription:'Em três conversas, faça ao menos uma pergunta de compreensão antes de apresentar sua própria interpretação.',estimatedMinutes:2,difficulty:'low',contexts:['conversa','relações'],contraindications:[],requiresOpportunity:true,sourceType:'deterministic-template'},
  {id:'communication-check-interpretation',title:'Checar antes de concluir',skill:'communication.interpretation_checking',description:'Quando perceber uma interpretação sobre a intenção de alguém, formule uma pergunta de esclarecimento antes de tratá-la como fato.',weeklyDescription:'Em uma conversa relevante, verifique diretamente uma interpretação antes de assumir a intenção da outra pessoa.',estimatedMinutes:3,difficulty:'low',contexts:['relações','incerteza'],contraindications:[],requiresOpportunity:true,sourceType:'deterministic-template'},
  {id:'observation-versus-inference',title:'Duas colunas mentais',skill:'metacognition.observation_inference',description:'Diante de uma conclusão importante, escreva uma frase com o que observou e outra com o que está inferindo.',weeklyDescription:'Em três situações relevantes, separe explicitamente “o que observei” de “o que estou concluindo”.',estimatedMinutes:3,difficulty:'low',contexts:['geral','relações'],contraindications:[],requiresOpportunity:false,sourceType:'deterministic-template'},
  {id:'assumption-one',title:'Um pressuposto necessário',skill:'metacognition.assumptions',description:'Escolha uma conclusão importante e identifique um pressuposto que precisaria ser verdadeiro para ela se sustentar.',weeklyDescription:'Em duas conclusões relevantes, identifique pelo menos um pressuposto necessário antes de decidir como agir.',estimatedMinutes:4,difficulty:'medium',contexts:['decisão','relações'],contraindications:[],requiresOpportunity:false,sourceType:'deterministic-template'},
  {id:'two-alternatives',title:'Duas alternativas plausíveis',skill:'critical.alternatives',description:'Antes de fechar uma conclusão, registre duas explicações alternativas que também sejam compatíveis com os fatos observados.',weeklyDescription:'Em duas situações relevantes, produza duas explicações alternativas antes de concluir.',estimatedMinutes:4,difficulty:'medium',contexts:['incerteza','relações'],contraindications:[],requiresOpportunity:false,sourceType:'deterministic-template'},
  {id:'boundary-clear-sentence',title:'Uma frase de limite',skill:'relations.boundaries',description:'Identifique uma situação adequada e formule em uma frase clara o que você pode, não pode ou prefere fazer.',weeklyDescription:'Em uma situação relevante, expresse claramente um limite sem acrescentar justificativas desnecessárias.',estimatedMinutes:4,difficulty:'medium',contexts:['relações','comunicação'],contraindications:[],requiresOpportunity:true,sourceType:'deterministic-template'},
  {id:'value-ten-minute-action',title:'Dez minutos em direção a um valor',skill:'values.small_action',description:'Escolha um valor já confirmado e defina uma ação de até dez minutos que expresse esse valor hoje.',weeklyDescription:'Escolha um valor confirmado e realize duas pequenas ações observáveis ligadas a ele em momentos diferentes da semana.',estimatedMinutes:10,difficulty:'medium',contexts:['valores','geral'],contraindications:[],requiresOpportunity:false,sourceType:'deterministic-template'},
]

export const PRACTICES_BY_SKILL=PRACTICES.reduce((map,practice)=>{
  const list=map.get(practice.skill)??[]
  list.push(practice)
  map.set(practice.skill,list)
  return map
},new Map<SkillId,PracticeDefinition[]>())

export function firstPracticeForSkill(skill:SkillId){return PRACTICES_BY_SKILL.get(skill)?.[0]??null}
