import {useEffect,useState} from 'react'
import {HashRouter,NavLink,Route,Routes} from 'react-router-dom'
import type {Session,User} from '@supabase/supabase-js'
import {supabase} from './supabase'
import WordCloud from './WordCloud'
import Suggestions from './Suggestions'

type Domain='Autorregulação'|'Flexibilidade'|'Socioemocional'|'Relações'|'Metacognição'
type Rec={id:string;createdAt:string;type:string;[k:string]:any}
const items:{id:string;domain:Domain;text:string}[]=[['ar1','Autorregulação','Hoje consegui iniciar algo importante mesmo sem vontade.'],['ar2','Autorregulação','Quando algo saiu do planejado, ajustei minha estratégia.'],['ar3','Autorregulação','Interrompi uma análise repetitiva quando ela deixou de produzir ação.'],['fx1','Flexibilidade','Percebi uma emoção desconfortável sem precisar eliminá-la imediatamente.'],['fx2','Flexibilidade','Notei um pensamento como pensamento, sem tratá-lo automaticamente como fato.'],['fx3','Flexibilidade','Fiz alguma ação coerente com algo que valorizo.'],['se1','Socioemocional','Regulei minha resposta emocional antes de agir impulsivamente.'],['se2','Socioemocional','Consegui me adaptar a uma mudança ou imprevisto.'],['se3','Socioemocional','Demonstrei curiosidade genuína diante de algo ou alguém.'],['re1','Relações','Em uma conversa, ouvi antes de preparar minha resposta.'],['re2','Relações','Expressei uma necessidade ou limite de forma clara e respeitosa.'],['re3','Relações','Evitei antecipar automaticamente a reação de outra pessoa.'],['mc1','Metacognição','Questionei pelo menos um pressuposto meu antes de concluir.'],['mc2','Metacognição','Distingui o que observei da interpretação que fiz.'],['mc3','Metacognição','Considerei pelo menos uma explicação alternativa plausível.']].map(([id,domain,text])=>({id,domain:domain as Domain,text}))
const domains:Domain[]=['Autorregulação','Flexibilidade','Socioemocional','Relações','Metacognição']
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN

async function loadRecords():Promise<Rec[]>{
  const {data,error}=await supabase.from('nexo_records').select('id,record_type,payload,created_at').order('created_at',{ascending:true})
  if(error)throw error
  return (data||[]).map((r:any)=>({id:r.id,type:r.record_type,createdAt:r.created_at,...r.payload}))
}
async function saveRecord(user:User,type:string,payload:any){
  const {error}=await supabase.from('nexo_records').insert({user_id:user.id,record_type:type,payload})
  if(error)throw error
}
async function deleteAll(){const {error}=await supabase.from('nexo_records').delete().neq('id','00000000-0000-0000-0000-000000000000');if(error)throw error}

function useRecords(){const[r,setR]=useState<Rec[]>([]),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{setR(await loadRecords())}finally{setLoading(false)}};useEffect(()=>{load()},[]);return[r,load,loading] as const}
function Card(p:any){return <div className="card"><h3>{p.title}</h3>{p.children}</div>}
function Range({label,value,set,max=10}:{label:string,value:number,set:(n:number)=>void,max?:number}){return <label>{label}: <b>{value}</b><input type="range" min="0" max={max} value={value} onChange={e=>set(+e.target.value)}/></label>}
function Auth(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'signup'>('login'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');const submit=async()=>{setBusy(true);setMsg('');try{if(mode==='signup'){const {error}=await supabase.auth.signUp({email,password});if(error)throw error;setMsg('Conta criada. Se a confirmação por e-mail estiver ativa, confirme o endereço antes de entrar.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}}catch(e:any){setMsg(e.message||'Não foi possível autenticar.')}finally{setBusy(false)}};return <main style={{maxWidth:520,margin:'8vh auto'}}><div className="eyebrow">acesso protegido</div><h1>Nexo</h1><div className="card form"><h3>{mode==='login'?'Entrar':'Criar conta'}</h3><p>Seus resultados só são carregados depois da autenticação e são isolados por usuário no banco.</p><label>E-mail (seu usuário)<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{msg&&<p>{msg}</p>}<button className="primary" disabled={busy||!email||password.length<6} onClick={submit}>{busy?'Aguarde...':mode==='login'?'Entrar':'Criar conta'}</button><button className="primary" style={{background:'#5d6a64'}} onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'Ainda não tenho conta':'Já tenho conta'}</button><small>A senha é gerenciada pelo Supabase Auth e não é salva na tabela de resultados nem no GitHub.</small></div></main>}

function Dashboard({user}:{user:User}){const[r,,loading]=useRecords(),cs=r.filter(x=>x.type==='checkin'),last=cs.at(-1);return <>{loading?<p>Carregando seus dados...</p>:<><div className="eyebrow">painel pessoal · {user.email}</div><h1>Hoje</h1><div className="grid"><Card title="Check-in">{last&&last.date===new Date().toISOString().slice(0,10)?'Concluído hoje':'Ainda não registrado'}</Card><Card title="Registros">{r.length} observações privadas</Card><Card title="Privacidade">Somente sua conta.</Card></div>{last&&<div className="grid">{domains.map(d=>{const v=items.filter(i=>i.domain===d).map(i=>last.responses[i.id]);return <Card title={d} key={d}>{mean(v).toFixed(2)}/5</Card>})}</div>}</>}</>}
function CheckIn({user}:{user:User}){const[resp,setResp]=useState<Record<string,number>>({});const[m,setM]=useState({energy:5,stress:5,connection:5,sleep:5,event:'',notes:''});const save=async()=>{if(Object.keys(resp).length<items.length)return alert('Responda todos os itens.');try{await saveRecord(user,'checkin',{version:'1.0',date:new Date().toISOString().slice(0,10),responses:resp,...m,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});alert('Check-in salvo na sua conta.');setResp({})}catch(e:any){alert(e.message)}};return <><div className="eyebrow">2 a 4 minutos</div><h1>Check-in diário</h1><div className="card"><p>1 = nada/muito difícil · 5 = muito/com facilidade. Itens autorais, não escala validada.</p>{items.map(i=><div className="item" key={i.id}><div><small>{i.domain}</small><p>{i.text}</p></div><div className="scale">{[1,2,3,4,5].map(n=><button key={n} className={resp[i.id]===n?'on':''} onClick={()=>setResp({...resp,[i.id]:n})}>{n}</button>)}</div></div>)}</div><div className="grid two">{(['energy','stress','connection','sleep'] as const).map(k=><Range key={k} label={{energy:'Energia',stress:'Estresse',connection:'Conexão social',sleep:'Sono'}[k]} value={m[k]} set={n=>setM({...m,[k]:n})}/>)}</div><div className="card form"><label>Evento importante<input value={m.event} onChange={e=>setM({...m,event:e.target.value})}/></label><label>Reflexão livre<textarea value={m.notes} onChange={e=>setM({...m,notes:e.target.value})}/></label><button className="primary" onClick={save}>Salvar check-in</button></div></>}
function Evolution(){const[r]=useRecords(),cs=r.filter(x=>x.type==='checkin');return <><div className="eyebrow">mudança intraindividual</div><h1>Evolução</h1><p>Ausências permanecem missing e não são tratadas como zero.</p>{domains.map(d=>{const vals=cs.map(c=>mean(items.filter(i=>i.domain===d).map(i=>c.responses[i.id])));return <div className="card trend" key={d}><h3>{d}</h3><b>{vals.length?mean(vals.slice(-7)).toFixed(2):'—'}</b><span> média recente</span><div className="bars">{vals.slice(-30).map((v,i)=><i key={i} style={{height:`${v/5*100}%`}}/>)}</div></div>})}</>}
function Relations({user}:{user:User}){const[f,setF]=useState<any>({context:'',quality:5,presence:5,listening:5,assertiveness:5,empathy:5,boundaries:5,connectionAfter:5,observed:'',inferred:'',assumption:'',alternatives:''});return <><div className="eyebrow">diário interpessoal</div><h1>Relações</h1><div className="card form"><label>Contexto<input value={f.context} onChange={e=>setF({...f,context:e.target.value})}/></label>{['quality','presence','listening','assertiveness','empathy','boundaries','connectionAfter'].map(k=><Range key={k} label={k} value={f[k]} set={n=>setF({...f,[k]:n})}/>)}{[['observed','O que realmente observei?'],['inferred','O que estou inferindo?'],['assumption','Que pressuposto estou fazendo?'],['alternatives','Que interpretações alternativas são plausíveis?']].map(([k,l])=><label key={k}>{l}<textarea value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<button className="primary" onClick={async()=>{try{await saveRecord(user,'relation',{version:'1.0',...f});alert('Interação salva.')}catch(e:any){alert(e.message)}}}>Salvar interação</button></div></>}
function Experiments({user}:{user:User}){const[f,setF]=useState<any>({situation:'',prediction:'',anticipatedEmotion:'',anticipatedIntensity:5,certainty:50,actual:'',observedEmotion:'',observedIntensity:5,learning:''});return <><div className="eyebrow">previsão → experiência → atualização</div><h1>Experimentos</h1><div className="grid two"><div className="card form"><h3>Antes</h3>{[['situation','Situação'],['prediction','Previsão'],['anticipatedEmotion','Emoção antecipada']].map(([k,l])=><label key={k}>{l}<textarea value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<Range label="Intensidade prevista" value={f.anticipatedIntensity} set={n=>setF({...f,anticipatedIntensity:n})}/><Range label="Certeza (%)" value={f.certainty} max={100} set={n=>setF({...f,certainty:n})}/></div><div className="card form"><h3>Depois</h3>{[['actual','O que aconteceu?'],['observedEmotion','Emoção observada'],['learning','O que aprendi?']].map(([k,l])=><label key={k}>{l}<textarea value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<Range label="Intensidade observada" value={f.observedIntensity} set={n=>setF({...f,observedIntensity:n})}/><button className="primary" onClick={async()=>{try{await saveRecord(user,'experiment',{version:'1.0',...f});alert('Experimento salvo.')}catch(e:any){alert(e.message)}}}>Salvar</button></div></div></>}
function Values({user}:{user:User}){const[f,setF]=useState({area:'relações',value:'',behavior:'',action:''});return <><div className="eyebrow">valor ≠ objetivo</div><h1>Valores</h1><div className="card form"><label>Área<select value={f.area} onChange={e=>setF({...f,area:e.target.value})}>{['relações','família','amizade','trabalho','estudo','saúde','criatividade','comunidade'].map(x=><option key={x}>{x}</option>)}</select></label><label>Valor<input value={f.value} onChange={e=>setF({...f,value:e.target.value})}/></label><label>Como quero me comportar?<textarea value={f.behavior} onChange={e=>setF({...f,behavior:e.target.value})}/></label><label>Ação comprometida<textarea value={f.action} onChange={e=>setF({...f,action:e.target.value})}/></label><button className="primary" onClick={async()=>{try{await saveRecord(user,'value',{version:'1.0',...f});alert('Salvo.')}catch(e:any){alert(e.message)}}}>Salvar</button></div></>}
function Reflection({user}:{user:User}){const[t,setT]=useState(''),[action,setAction]=useState('');return <><div className="eyebrow">ACT + metacognição</div><h1>Pensamento não é fato</h1><div className="grid two"><div className="card form"><label>Pensamento<textarea value={t} onChange={e=>setT(e.target.value)}/></label>{t&&<blockquote>Estou tendo o pensamento de que: <b>{t}</b></blockquote>}<label>Se eu não precisasse eliminá-lo, qual ação seria coerente com o que valorizo?<textarea value={action} onChange={e=>setAction(e.target.value)}/></label><button className="primary" onClick={async()=>{try{await saveRecord(user,'reflection',{version:'1.0',thought:t,action});alert('Reflexão salva.')}catch(e:any){alert(e.message)}}}>Salvar reflexão</button></div><div className="card"><h3>Auditoria do raciocínio</h3>{['Qual é meu propósito?','O que observei e o que inferi?','Que pressupostos estou usando?','Que evidência sustenta a inferência?','Qual ponto de vista alternativo merece consideração?','Quais implicações seguem?'].map(q=><p key={q}>{q}</p>)}</div></div></>}
function Review({user}:{user:User}){const qs=['O que ficou mais fácil?','O que ficou mais difícil?','Quando agi conforme meus valores?','Onde tentei controlar algo fora do meu controle?','Que interação aumentou conexão?','Que conversa evitei?','Qual pressuposto foi questionado?','Onde previsão e experiência divergiram?','O que aprendi?','Qual habilidade praticarei na próxima semana?'];const[a,setA]=useState<Record<number,string>>({});return <><div className="eyebrow">uma habilidade por vez</div><h1>Minha semana</h1><div className="card form">{qs.map((q,i)=><label key={q}>{q}<textarea value={a[i]||''} onChange={e=>setA({...a,[i]:e.target.value})}/></label>)}<button className="primary" onClick={async()=>{try{await saveRecord(user,'review',{version:'1.0',answers:a});alert('Revisão salva.')}catch(e:any){alert(e.message)}}}>Salvar revisão</button></div></>}
function Data({user}:{user:User}){const[r,load]=useRecords();const exp=()=>{const b=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),account:user.email,records:r},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='nexo-backup.json';a.click()};return <><div className="eyebrow">conta privada</div><h1>Dados e privacidade</h1><div className="card form"><p>Os registros desta página pertencem ao usuário autenticado <b>{user.email}</b>. O banco usa Row Level Security para impedir acesso entre contas.</p><button className="primary" onClick={exp}>Exportar meus dados</button><label>Importar meu backup<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const j=JSON.parse(await f.text());for(const x of j.records||[]){const {id,createdAt,type,...payload}=x;await saveRecord(user,type,payload)}load()}}/></label><button className="danger" onClick={async()=>{if(confirm('Excluir permanentemente todos os seus resultados?')){try{await deleteAll();await load()}catch(e:any){alert(e.message)}}}}>Excluir meus resultados</button><p>{r.length} registros associados à sua conta.</p></div></>}
function Science(){return <><div className="eyebrow">transparência metodológica</div><h1>Como este sistema foi construído</h1><Card title="Privacidade"><p>Autenticação por Supabase Auth. Resultados armazenados em Postgres com RLS por usuário. Senhas não ficam na tabela de resultados nem no repositório.</p></Card><Card title="OECD"><p>OECD (2025). <i>Skills that Matter for Success and Well-being in Adulthood</i>. DOI: 10.1787/6e318286-en.</p><p>Enquadramento de habilidades socioemocionais em adultos, não escala clínica diária.</p></Card><Card title="ACT"><p>Gloster et al. (2021). <i>Psy-Flex: A contextually sensitive measure of psychological flexibility</i>. DOI: 10.1016/j.jcbs.2021.09.001.</p><p>O Nexo não reproduz itens protegidos do Psy-Flex ou CompACT.</p></Card><Card title="Paul e Elder"><p>Foundation for Critical Thinking, <i>The Elements of Reasoning and the Intellectual Standards</i>.</p><p>Referencial de autorregulação e metacognição do raciocínio.</p></Card></>}
function Layout({user}:{user:User}){const links=[['/','Hoje'],['/checkin','Check-in'],['/evolucao','Evolução'],['/sugestoes','Sugestões'],['/nuvem','Nuvem'],['/relacoes','Relações'],['/experimentos','Experimentos'],['/valores','Valores'],['/reflexao','Reflexão'],['/revisao','Revisão'],['/dados','Dados'],['/ciencia','Ciência']];return <div className="app"><aside><h2>Nexo</h2><small>{user.email}</small><nav>{links.map(([u,l])=><NavLink to={u} key={u}>{l}</NavLink>)}</nav><button className="primary" style={{marginTop:24}} onClick={()=>supabase.auth.signOut()}>Sair</button></aside><main><Routes><Route path="/" element={<Dashboard user={user}/>}/><Route path="/checkin" element={<CheckIn user={user}/>}/><Route path="/evolucao" element={<Evolution/>}/><Route path="/sugestoes" element={<Suggestions/>}/><Route path="/nuvem" element={<WordCloud/>}/><Route path="/relacoes" element={<Relations user={user}/>}/><Route path="/experimentos" element={<Experiments user={user}/>}/><Route path="/valores" element={<Values user={user}/>}/><Route path="/reflexao" element={<Reflection user={user}/>}/><Route path="/revisao" element={<Review user={user}/>}/><Route path="/dados" element={<Data user={user}/>}/><Route path="/ciencia" element={<Science/>}/></Routes><footer>Ferramenta de auto-observação e desenvolvimento pessoal. Não realiza diagnóstico psicológico ou psiquiátrico e não substitui acompanhamento profissional.</footer></main></div>}
export default function App(){const[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(s);setReady(true)});return()=>subscription.unsubscribe()},[]);if(!ready)return <main><p>Verificando sessão...</p></main>;return session?<HashRouter><Layout user={session.user}/></HashRouter>:<Auth/>}
